AdminUser/urls.py
from django.urls import path
from . import views
app_name='AdminUser'

urlpatterns = [
	path('home/',views.cmpview),
]	

PublicUser/urls.py
from django.urls import path

from . import views
app_name='PublicUser'

urlpatterns = [
	path('home/', views.home),
	path('complain/',views.complaint),
	path('about/',views.about),
	path('wastepickup/',views.wastepickup),
	path('bulkpickup/',views.bulkpickup),
	path('getdumpster/',views.getdumpster),
	path('solution/',views.solution),
	path('solidwaste/',views.solidwaste),
	path('cmphistory/<int:id>/',views.cmphistory, name="cmphistory")
]

WasteManagement/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup2/',views.signup2),
    path('signup1/',views.signup),
    path('login1/',views.login1),
    path('login2/',views.login2),
    path('logout/',views.logout_call),
    path('office/', include('AdminUser.urls')),
    path('PublicUser/',include('PublicUser.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AdminUser/models.py
from django.db import models

# Create your models here.

PublicUser/models.py
from django.db import models
from WasteManagement.models import Public



# Create your models here.
class Complaint(models.Model):
	user=models.ForeignKey (Public,on_delete=models.CASCADE)
	compType=models.CharField(max_length=20)
	location = models.CharField(max_length=20, blank=True)
	desc=models.CharField(max_length=200)
	pic=models.ImageField(upload_to='complainimage',blank=False)
	dated = models.DateTimeField(auto_now_add = True)
	current_status = models.CharField(max_length=40, blank=True)

WasteManagement/models.py
from django.db import models
from django.contrib.auth.models import User

class Public(models.Model):
	user=models.OneToOneField(User, on_delete=models.CASCADE)
	mobile=models.CharField(max_length=12)
	pic =models.ImageField(upload_to='proimage',blank=True)


class Office(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	email=models.CharField(max_length=30)
	contact=models.CharField(max_length=12)

AdminUser/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from PublicUser.models import Complaint
from django.views.generic import UpdateView
from django.contrib.auth.decorators import login_required
# Create your views here.

def cmpview(request):
	cmp_data = Complaint.objects.all()
	if request.method == 'POST':
		current_status = request.POST.getlist('current_status')
		id_ = request.POST.getlist('id')
		print(id_)
		print(current_status)
		for i in range(len(id_)):
			comp = Complaint.objects.filter(id=id_[i])
			comp.update(current_status=current_status[i])
		return redirect('/office/home/')
	return render(request,'cmphistory.html', {'data':cmp_data})
	

PublicUser/views.py
from django.shortcuts import render, redirect
from .models import Complaint
from WasteManagement.models import Public
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from . models import Complaint
from django.http import HttpResponse

# Create your views here.

def cmphistory(request,id):
	p = Public.objects.get(user__id=id)
	c = Complaint.objects.filter(user_id=p.id)
	url = '/PublicUser/complain'
	if len(c)>0:

		return render(request,'publiccmphistory.html',{'object_list': c})
	else:
		return HttpResponse('<script> alert("No Complaint Found!");\
		window.location="%s"</script>'%url)


def home(request):
	return render(request, 'Public.html')


@login_required(login_url = '/login1/')
def complaint(request):
	if request.method=='POST':
		complain=request.POST['complain']
		location = request.POST['location']
		desc=request.POST['desc']
		pic=request.FILES['pic']
		curr_status = request.POST['current_status']
		uObj=Public.objects.get(user__username=request.user)
		o= Complaint(user=uObj,compType=complain,desc=desc,pic=pic,location=location, current_status=curr_status)
		o.save()
		return redirect('/PublicUser/home/')
	return render(request,'complain.html')
	

def about(request):
	return render(request,'about.html')
def wastepickup(request):
	return render(request,'2nd.html')
def bulkpickup(request):
	return render(request,'3rd.html')
def getdumpster(request):
	return render(request,'1st.html')
def solution(request):
	return render(request,'4th.html')
def solidwaste(request):
	return render(request,'5th.html')

WasteManagement/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Public, Office
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password

def signup(request):

	if request.method=='POST':
		fname=request.POST['fname']
		lname=request.POST['lname']
		mob=request.POST['number']
		email=request.POST['email']
		uname=request.POST['username']
		passwd=request.POST['password']
		pic=request.FILES['pic']
		u=User(first_name=fname,last_name=lname,email=email,username=uname,password=make_password(passwd))
		u.save()
		p=Public(user=u,mobile=mob,pic=pic)
		p.save()
		return redirect('/login1/')

	return render(request,'signup.html')

def signup2(request):
	if request.method=='POST':
		email=request.POST['email']
		empID=request.POST['empID']
		contact=request.POST['contact']
		passwd=request.POST['password']
		u = User(username=empID,password=make_password(passwd))
		u.save()
		o=Office(user=u,email=email,contact=contact,)
		o.save()
		return redirect('/login2/')
	return render(request,'signup2.html')

def login1(request):
	url = '/login1/'
	if request.method=='POST':
		#print("hxbskhgshy")
		uname=request.POST['username']
		passwd=request.POST['password']
		currentUser=authenticate(username=uname,password=passwd)
		if currentUser:
			login(request,currentUser)
			u=Public.objects.get(user__username=request.user)
			return redirect('/PublicUser/home/')
		else:
			return HttpResponse('<script> alert("Invalid Username and Password");\
		window.location="%s"</script>'%url)

	return render(request, 'login1.html')
def login2(request):
	url = '/login2/'
	if request.method=='POST':
		#print("hxbskhgshy")
		empID=request.POST['empID']
		passwd=request.POST['password']
		currentUser=authenticate(username=empID,password=passwd)
		if currentUser:
			login(request,currentUser)
			o=Office.objects.get(user__username=request.user)
			return redirect('/office/home/')

		else:
			return HttpResponse('<script> alert("Invalid Employee Id and Password");\
		window.location="%s"</script>'%url)
			

	return render(request, 'login2.html')



def logout_call(request):
	logout(request)
	return redirect('/PublicUser/home/')

templates/1st.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <style type="text/css">
    .btn_color:hover{
      color: black !important;
    }
  </style>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/vipul.css'%}">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <title>Get a Dumpster</title>
</head>
<body>

<!--Navbar--->
<div style="background-color: whitesmoke">
<nav class="navbar navbar-expand-lg navbar-light ">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>'

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/PublicUser/home/" style="color: black"><img src="{% static 'img/d.png' %}" width="50px">  <span class="sr-only">(current)</span></a>
      </li>
      <li >
        <a class="nav-link " href="/PublicUser/home/" id="" role=""  aria-haspopup="" aria-expanded="" style="color: green">
           Home
        </a>
       
      </li>
     
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"style="color: green">
          Our Services
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #BAE18D">
          <a class="dropdown-item" href="/PublicUser/getdumpster/">Get A Dumpster</a>
          <a class="dropdown-item" href="/PublicUser/bulkpickup/">Scheduled Bulk Pickup</a>
          <a class="dropdown-item" href="/PublicUser/wastepickup/">Order Waste Pickup</a>
          <a class="dropdown-item" href="/PublicUser/solution/">Recycling & Sustainability</a>
          <a class="dropdown-item" href="/PublicUser/solidwaste/">BAGSTER® BAG</a>
          
          
        </div>
      </li>
      
     
      <li >
        <a class="nav-link " href="/PublicUser/about/" id="" role="" aria-haspopup="" aria-expanded="false" style="color: green">
          About Us
        </a>
      </li>
      <li >
        <a class="nav-link " href="/PublicUser/complain/" id="" role=""  aria-haspopup="" aria-expanded="" style="color: green">
           Complaints
        </a>
      </li>
     
    </ul>

 {% if request.user.is_authenticated%}

    <ul class="navbar-nav ml-auto mr-auto padding">
        <li class="nav-item dropdown">
          <a style="color: green;" href="/logout/" class="nav-link btn btn-outline-success btn_color">Logout</a>
        </li>
        
      </ul>
 {%else%}

      <ul class = "navbar-nav ml-auto mr-auto padding">
        <li class="">
          <a href="/signup1/" style="color: green;" class="nav-link btn btn-outline-success btn_color">SignUp</a>
          
        </li>
        <li class="">
          <a href="/login1/" style="color: green;" class="nav-link btn btn-outline-success btn_color">Login</a>
          
        </li>
        
        
      </ul>
    
  
  {% endif %}

  </div>
</nav>
</div>



<!---Navbar close-->

<!--body--->
<div class="container-fluid">
  <h1>Get a Dumpster</h1><br></div>
   <!---- main work----->
    <div class="container-fluid row">
    <div class="card mb-3">
  
  <div class="card-body">
    <h5 class="card-title">TEMPORARY DUMPSTER SOLUTIONS</h5>
    <p class="card-text">Getting a temporary dumpster from Waste Management is easy. Find the perfect size for your needs, order it, schedule delivery and pay, all with just a few clicks. After that, fill it up and we’ll take care of the rest. Advantages of Waste Management roll-off dumpsters include:
</p>
      <ul>
        <li>24/7 access with online ordering, scheduling and account management</li>
          <li>Flexible, reliable, and professional delivery and pickup</li>
          <li>Wide selection of dumpster sizes from 20 yard to 40 yard</li>
           <li>Instant online pricing</li>
           <li>Rush service available</li>

                    

          
      </ul>
    
  </div>
  <img src="{% static 'img/wm2new.jpg' %}" height="500px" class="card-img-top" alt="...">
</div>
        
     <div class="container-fluid">
    <div class="card md-3">
  
  <div class="card-body">
    <h5 class="card-title">MANAGING YOUR ROLL-OFF DUMPSTER NEEDS THE RIGHT WAY</h5>
    <p class="card-text">From large construction and renovation projects to commercial cleanouts or even spring cleaning, if you find that you need a roll-off dumpster, Waste Management has a variety of options to get rid of that waste responsibly.
      Every construction site will inevitably generate waste. Instead of worrying about what to do with leftover drywall scraps or roofing shingles, let us help you find the right roll-off dumpster for your construction project. We have a variety of sizes to choose from, and convenient online tools for ordering and scheduling a delivery. Then, all you have to do is fill your roll-off with debris and we’ll handle the rest.
</p>
      
  </div>
  <img src="{% static 'img/rendetion-new.jpg' %}" height="500px" class="card-img-top" alt="...">
</div>




<!--body-->

<!--- Connect -->
<div class="container-fluid padding">
  <div class="row text-center padding">
    <div class="col-12">
      <h2>Connect With Us</h2>
    </div>
    <div class="col-12 social padding">
      <a href="www.facebook.com"><i class="fab fa-facebook"></i></a>
      <a href="www.twitter.com"><i class="fab fa-twitter"></i></a>
      <a href="www.google.com"><i class="fab fa-google-plus-g"></i></a>
      <a href="www.instagram.com"><i class="fab fa-instagram"></i></a>
      <a href=""><i class="fab fa-youtube"></i></a>

    </div>
  </div>
</div>


<!--- Footer -->
<footer>
<div class="container-fluid padding">
  <div class="row text-center">
    <div class="col-md-4">
      <img src="{% static 'img/chasma.png' %}" width="190px">
      <hr class="light">
      
    </div>
    <div class="col-md-4">
      <hr class="light">
      <h5>Contact Us</h5>
      <hr class="light">
      <p><a href="www.Whatsapp.com"><i class="fab fa-whatsapp"></i></a>&nbsp;Us  0000000000</p>
      <p>Email- nagarnigam@gmail.com</p>
      <p>Address- T-1,B-3,Capital Mall Bhopal</p>
    </div>
    <div class="col-md-4">
      <hr class="light">
      <h5>Our Timing</h5>
      <hr class="light">
      <p> Monday:9am-5pm</p>
      <p>Saturday: 10am-4pm</p>
      
  </div>
  <div class="col-12">
    <hr class="light-100">
    <h5>Copyright:nagar@nigam@gmail.com</h5>
  </div>
</div>

</div>
</footer>

</body>
</html>


</body>
</html>

templates/complain.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

<style type="text/css">
    .btn_color:hover{
      color: black !important;
    }
  </style>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/vipul.css'%}">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <style>
    #complaint_box{
      border: 1px solid black;
    }
    .my_complaint{
      color: green;
      text-decoration: none;
    }
    .my_complaint a h5 hover{
      color: #A6E22B !important;
      font-weight: bold;
      border: 1px solid black;
    }

  </style>
  <style type="text/css">
    .btn_color:hover{
      color: black !important;
    }
  </style>



</head>

<body>
 <div style="background-color: whitesmoke">
<nav class="navbar navbar-expand-lg navbar-light ">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>'

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/PublicUser/home/" style="color: black"><img src="{% static 'img/d.png' %}" width="50px">  <span class="sr-only">(current)</span></a>
      </li>
      <li >
        <a class="nav-link " href="/PublicUser/home/" id="" role=""  aria-haspopup="" aria-expanded="" style="color: green">
           Home
        </a>
       
      </li>
     
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"style="color: green">
          Our Services
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #BAE18D">
          <a class="dropdown-item" href="/PublicUser/getdumpster/">Get A Dumpster</a>
          <a class="dropdown-item" href="/PublicUser/bulkpickup/">Scheduled Bulk Pickup</a>
          <a class="dropdown-item" href="/PublicUser/wastepickup/">Order Waste Pickup</a>
          <a class="dropdown-item" href="/PublicUser/solution/">Recycling & Sustainability</a>
          <a class="dropdown-item" href="/PublicUser/solidwaste/">BAGSTER® BAG</a>
          
          
        </div>
      </li>
      
     
      <li >
        <a class="nav-link " href="/PublicUser/about/" id="" role="" aria-haspopup="" aria-expanded="false" style="color: green">
          About Us
        </a>
      </li>
      <li >
        <a class="nav-link " href="/PublicUser/complain/" id="" role=""  aria-haspopup="" aria-expanded="" style="color: green">
           Complaints
        </a>
      </li>
     
    </ul>

 {% if request.user.is_authenticated%}

    <ul class="navbar-nav ml-auto mr-auto padding">
        <li class="nav-item dropdown">
          <a style="color: green;" href="/logout/" class="nav-link btn btn-outline-success btn_color">Logout</a>
        </li>
        
      </ul>
 {%else%}

      <ul class = "navbar-nav ml-auto mr-auto padding">
        <li class="">
          <a href="/signup1/" style="color: green;" class="nav-link btn btn-outline-success btn_color">SignUp</a>
          
        </li>
        <li class="">
          <a href="/login1/" style="color: green;" class="nav-link btn btn-outline-success btn_color">Login</a>
          
        </li>
        
        
      </ul>
    
  
  {% endif %}

  </div>
</nav>
</div>
  <br><div class="container">
    <button>
    <a  class="my_complaint" href="{% url 'PublicUser:cmphistory' id=request.user.id %}"><h5>Complaint History</h5></a></button>
  </div>
  <br>
  <div class="container">
    <div id="complaint_box">
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1">
      <h2 class="text-center">BHOPAL MUNCIPAL-WASTE MANAGEMENT</h2>
    </div>
    </div>
  </div><br><br>
  
  <div class="container row">
   
      <div class="col-md-6 offset-md-3">
    
   <form class="form-group jumbotron" method="post" enctype="multipart/form-data">
    {% csrf_token %}
     <h3>Register your Complaint!</h3><br>
     <p><u class=""><b>NOTE</b></u> - All fields are mandatory.</p><br>
     Complaint Type: <select name="complain" class="form-control">
      <option value="Tree">Tree Cutting</option>
      <option value="Sewage">Sewage Complaint</option>
      <option value="LampPost">Lamp Post Complaint</option>
      <option value="other">Other</option>

       
     </select><br>
     Location: <input type="text" name="location" class="form-control"><br>
     Description: <textarea rows="5" name="desc" class="form-control"></textarea><br>
     Upload Image: <input type="file" name="pic" class="form-control"><br><br>
     <input type="hidden" name="current_status" value="Registered">
     <div class="form-group">
     <input type="submit" value="SUBMIT" class="form-control btn btn-success">
    </div>
   </form>
   </div>
  </div>
</div>
</div><br>

<div class="container-fluid padding">
  <div class="row text-center padding">
    <div class="col-12">
      <h2>Connect With Us:</h2>
    </div>
    <div class="col-12 social padding">
      <a href="www.facebook.com"><i class="fab fa-facebook"></i></a>
      <a href="www.twitter.com"><i class="fab fa-twitter"></i></a>
      <a href="www.google.com"><i class="fab fa-google-plus-g"></i></a>
      <a href="www.instagram.com"><i class="fab fa-instagram"></i></a>
      <a href=""><i class="fab fa-youtube"></i></a>

    </div>
  </div>
</div>

<!--Footer wark start-->
<footer>
  <div class="container-fluid padding">
    <div class="row text-center">
      <div class="col-md-4">
        <img src="{% static 'img/chasma.png' %}" width="190px">
        <hr class="light">
        
      </div>
      <div class="col-md-4">
        <hr class="light">
        <h5>Contact Us</h5>
        <hr class="light">
        <p><a href="www.Whatsapp.com"><i class="fab fa-whatsapp"></i></a>&nbsp;Us  0000000000</p>
        <p>Email- nagarnigam@gmail.com</p>
        <p>Address- T-1,B-3,Capital Mall Bhopal</p>
      </div>
      <div class="col-md-4">
        <hr class="light">
        <h5>Our Timing</h5>
        <hr class="light">
        <p> Monday:9am-5pm</p>
        <p>Saturday: 10am-4pm</p>
        <p>Sunday: Off</p>
        
    </div>
    <div class="col-12">
      <hr class="light-100">
      <h5>Copyright:nagar@nigam@gmail.com</h5>
    </div>
  </div>
  
  </div>
  </footer>

       <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
</body>
</html>